vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeEndOfBuffer", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeFloatNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeFloatBorder", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeTitleBar", { fg = "#ffffff", bg = "NONE" })

vim.api.nvim_set_hl("TelescopeBorder", { fg = "#262626", bg = "#282828" })
vim.api.nvim_set_hl("TelescopeNormal", { bg = "#282828" })
vim.api.nvim_set_hl("TelescopePreviewBorder", { fg = "#282828", bg = "#282828" })
vim.api.nvim_set_hl("TelescopePreviewNormal", { bg = "#282828" })
vim.api.nvim_set_hl("TelescopePreviewTitle", { fg = "#282828", bg = "#fbf1c7" })
vim.api.nvim_set_hl("TelescopePromptBorder", { fg = "#262626", bg = "#262626" })
vim.api.nvim_set_hl("TelescopePromptNormal", { fg = "#fbf1c7", bg = "#262626" })
vim.api.nvim_set_hl("TelescopePromptPrefix", { fg = "#fbf1c7", bg = "#262626" })
vim.api.nvim_set_hl("TelescopePromptTitle", { fg = "#fbf1c7", bg = "#282828" })
vim.api.nvim_set_hl("TelescopeResultsBorder", { fg = "#fbf1c7", bg = "#282828" })
vim.api.nvim_set_hl("TelescopeResultsNormal", { bg = "#282828" })
vim.api.nvim_set_hl("TelescopeResultsTitle", { fg = "#fbf1c7", bg = "#282828" })
