vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeEndOfBuffer", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeFloatNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeFloatBorder", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeTitleBar", { fg = "#ffffff", bg = "NONE" })

vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#262626", bg = "#3c3836" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { fg = "#fbf1c7", bg = "#3c3836" })
-- vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { fg = "#282828", bg = "#282828" })
-- vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = "#282828" })
-- vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { fg = "#282828", bg = "#fbf1c7" })
-- vim.api.nvim_set_hl(0, "TelescopePromptBorder", { fg = "#262626", bg = "#262626" })
-- vim.api.nvim_set_hl(0, "TelescopePromptNormal", { fg = "#fbf1c7", bg = "#262626" })
-- vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { fg = "#282828", bg = "#fbf1c7" })
-- vim.api.nvim_set_hl(9, "TelescopePromptTitle", { fg = "#fbf1c7", bg = "#282828" })
-- vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { fg = "#fbf1c7", bg = "#282828" })
-- vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = "#282828" })
-- vim.api.nvim_set_hl(0, "TelescopeResultsTitle", { fg = "#282828", bg = "#fbf1c7" })
